# fly.toml app configuration file generated for escribista on 2023-07-23T13:53:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "escribista"
primary_region = "mad"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
